### ISSUE TITLE
LEDs- non-responsive? 

### ISSUE THREAD

**Issue by sarahmkirk** [EtalumaSupport/LumaViewPro#101]
The LED sliders in the channel controls are not turning the LEDs off an on. I don't think this is a hardware issue because no one has  touched anything inside the microscope. The LEDS also don't turn on if channels are acquired in protocol.

**Comment by sarahmkirk** [comment]
I am also having camera connection problems and I feel like these might be related

**Comment by ericweiner** [comment]
I would unplug the USB Hub from the computer, unplug the power from everything, then plug in the power first, then USB Hub.

**Comment by ericweiner** [comment]
but also posting the log would be helpful so we can see if LVpro is connecting to the camera/board on init.

**Comment by iwaniec** [comment]
Logging within hardware classes has been implemented.
