### ISSUE TITLE
Crash - Pushing Autofocus  / Set All Z button causes immediate* Crash

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#103]
*Clicking on the Autofocus button when Z-axis is at home sometimes doesn't crash on the first click, but it does on the 2nd click. 
[LVP_log 1659556343346.txt](https://github.com/EtalumaSupport/LumaViewPro/files/9254597/LVP_log.1659556343346.txt)
![Autofocus_Set all Z_2022-08-03 125612](https://user-images.githubusercontent.com/107218299/182698723-e09ae44d-fa13-4fe1-ab16-505df9a8f2c2.png)

**Comment by kmcleaster** [comment]
When positioning and focusing on dirt on a microscope slide, (brightfield, ambient illumination, 4X objective), the Autofocus function does not cause a crash.

**Comment by iwaniec** [comment]
Set all Z has been repaired and uploaded.

**Comment by kmcleaster** [comment]
The Set all Z , Set Z, and Go To Z work fine now.
However Autofocus still crashes if the Z-stage & Objective are very far from something to focus upon. 
After the stages initialize (Z axis at home) and xy are positioned to take an image, clicking Autofocus moves Z briefly and stops. Clicking it again causes a crash.

**Comment by iwaniec** [comment]
Repaired.
