### ISSUE TITLE
GUI - Exposure Setting is not updated on other channels

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#104]
Note that the camera exposure setting is common to all channels. When setting an exposure (ms) in one channel and then switching to another channel, the exposure setting is _**displayed**_ with whatever the previous or defaulted setting that was made in that particular channel's GUI.  The display **_should_**  show the most recently set exposure , irrespective of the channel. You should be able to set the exposure in each channel, but that exposure will prevail for all channels. A custom device with multiple cameras would need separate exposure settings for each camera.

**Comment by kmcleaster** [comment]
The camera exposure and gain settings both, are common to all channels. Maybe it would be best to include them under the microscope settings submenu, but to display these common controls on all channels . This would allow the user to achieve the best exposure without clicking between the color submenus.

**Comment by laneniles** [comment]
Question is whether the exposure setting should be the same for all channels. 

There will have to be a way to enable the brightfield exposure to be different from the color led channels or else the bf will be saturated when an image is obtained under a color channel or a grayscaled image in bf will result, most likely, in a dark image in the color channels. 

I would suggest enabling the two camera settings (gain, exposure) for each channel to be set independently, and do a stopstream/startstream number on the camera when any one is changed. The change could be invoked with the mouse-up event for the slider, although setting up these parameters is always much simpler when the changed settings are sent to the camera on the slider_change event.

**Comment by kmcleaster** [comment]
@laneniles points out some things I failed to consider. Please disregard my comments!

**Comment by laneniles** [comment]
Recommend designating closure of this issue
