### ISSUE TITLE
Protocol - Cannot pause nor stop a running protocol

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#105]
There is no way to stop a running protocol. I was trying to create a new one, it began running, and there was no way to stop it.
We should consider an eStop button on the main GUI and stop/pause controls in the XY stage control.
[LVP_log 1659569455590.txt](https://github.com/EtalumaSupport/LumaViewPro/files/9255735/LVP_log.1659569455590.txt)

**Comment by kmcleaster** [comment]
I learned the you can click on the Running Scan or Run Full Protocol buttons to stop a running protocol. We probably still need an eStop button .

**Comment by iwaniec** [comment]
"you can click on the Running Scan or Run Full Protocol buttons to stop a running protocol." In a team meeting, we elected to maintain this action.
