### ISSUE TITLE
GUI- Multicolor image Icon - click >> LVPro nonresponsive

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#106]
Clicking on the red-blue-green image capture icon at the bottom of the screen causes LV Pro to become non-responsive if you click it twice
![RGB Folder Icon_ not_responding](https://user-images.githubusercontent.com/107218299/182744839-eb015d00-6e45-4fcc-849d-c7f82e248c83.png)
.

**Comment by iwaniec** [comment]
This is not a folder. It is an icon to take a multicolor image.

**Comment by kmcleaster** [comment]
I believe the issue is due to the Z-home timeout.  If the Z-axis is not at home, clicking the 3color icon homes Z but does not activate the leds. Clicking it a second time causes a crash. Could this be a safety thing to avoid stage collision with an objective lens? If you click the 3color icon with Z at home, the leds fire once each color.

**Comment by kmcleaster** [comment]
I believe I have confirmed that this is due to the Z-axis timeout. It does not crash as long as it get to home before the timeout. If the Z axis is near the top , the bug is reproduceable. Issue #84

**Comment by kmcleaster** [comment]
Clicking the Icon sends Z-axis to home right before the crash
[LVP_log 1660775481157.txt](https://github.com/EtalumaSupport/LumaViewPro/files/9366463/LVP_log.1660775481157.txt)
.

**Comment by iwaniec** [comment]
Z-axis home has been re-written to be more robust. If possible, please test again.
