### ISSUE TITLE
GUI -- Illumination controls

### ISSUE THREAD

**Issue by laneniles** [EtalumaSupport/LumaViewPro#108]
When the led in one channel is on, as set by the button, opening the control panel for a different channel shuts off that led. This is OK, as such, but reopening the control panel for that now-off led shows the button highlighted and in the on position, requiring the control to be set to off and then to on again to turn on the led.

Also, the new illumination setting is sent to the led controller on the mouse-up event of the slider. In order to determine correct or optimal illumination conditions when setting up a run, it is infinitely easier to have the led control use a slider move event instead so that the illumination scales up and down as the slider is moved to optimize.

**Comment by iwaniec** [comment]
LED toggle button corrected. In talking to hardware, trying to update continuously causes strobing behaviors. Needs discussion. We open a new issue if this is still preferred.
