### ISSUE TITLE
Post Processing- not responding then crashes

### ISSUE THREAD

**Issue by sarahmkirk** [EtalumaSupport/LumaViewPro#112]
I'm not sure if either of the functions (create AVI or stitch) have been added yet, but if they have they are unable to load and the program times out. Correct me if I'm wrong but I remember Kevin showing a stitched imaged of the slide. Was that just an example of the software and it hasn't yet been added to LVP?

**Comment by iwaniec** [comment]
This was implemented outside the main code and will need to be added to LVP.

**Comment by iwaniec** [comment]
No longer crashes. Merge with issue #73
