### ISSUE TITLE
GUI -- Protocol--User interface becomes sluggish

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#113]
After running a test protocol, I am finding that the user interface becomes quite sluggish. Clicking on anything on the UI can take at least 2 seconds before anything happens.

For example, right now switching from the Focus Menu button to the XY stage control button is taking 7 seconds to finish.
[LVP_log 1660779207700.txt](https://github.com/EtalumaSupport/LumaViewPro/files/9366749/LVP_log.1660779207700.txt)
.

**Comment by iwaniec** [comment]
I believe this has been addressed. Please reopen if it continues.
