### ISSUE TITLE
GUI - X , Y, Z, position indicators not properly updated.

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#114]
After running a protocol , the X and Y indicators of the stage contol submenu nor the Z position indicator of the Focus indicator show the correct, current position. They are not updated after the protocol is complete. In the figure, if you set X&y manually and then run a protocol. Returning to the stage control submenu shows the previously entered coordinates, not the current position at the end of the protocol
![XY_not_updated](https://user-images.githubusercontent.com/107218299/185272618-cf3601ca-2a6d-4a76-9435-6719ede700ec.png)
.

**Comment by kmcleaster** [comment]
Tested, fixed.

**Comment by kmcleaster** [comment]
For the Z axis, if you load a previously saved protocol and go to the first step , the X & Y coordinates in the white boxes are correct, however in the Focus tab, the Z-coordinate is zero. For creating protocols I feel the need to know where I am at all times. A floating or bottom menu bar with xy&z would be helpful.

**Comment by EtalumaSupport** [comment]
appears to have been fixed
