### ISSUE TITLE
crash- change frame size 

### ISSUE THREAD

**Issue by sarahmkirk** [EtalumaSupport/LumaViewPro#117]
in microscope settings any change to the frame size causes an immediate crash

**Comment by laneniles** [comment]
same happens when using mouse scroll button to change image size and then clicking outside of image window

**Comment by kmcleaster** [comment]
This is partially the same as issue #103

**Comment by iwaniec** [comment]
Frame size issue is resolved. Now automatically requires the values to be multiples of 4. (camera requirement)
