### ISSUE TITLE
GUI - Focus - Manual controls increment beyond current SW limit of 12,000 microns.

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#119]
When the Z-axis reaches its upper limit of travel, the manual "UP" controls can advance the Z-stage beyond its SW set limit of 12,000 microns. **Also, set the the stage limit to 14,000 microns.**
The 12,000 micron limit was chosen earlier as a hardware-safety precaution.

![Z_increment_up_beyond_sw_limit](https://user-images.githubusercontent.com/107218299/186509048-1cca74ba-351b-4083-9ef2-f1a048320141.png)
*

**Comment by iwaniec** [comment]
Complete.
