### ISSUE TITLE
Run Protocol closes app

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#12]
Appears to start a 10 second countdown then closes.

**Comment by iwaniec** [comment]
Same issue as the capture button. Currently closes if the save folders do no exist. Will fix this.

**Comment by iwaniec** [comment]
temporary fix that it will print save folder does not exist instead of crashing.

**Comment by iwaniec** [comment]
Folder selection has been improved and as long as someone selects a directory using the folder selection button, it should work properly.
