### ISSUE TITLE
Camera - Image is not centered in the latest version

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#120]
When looking at a brightfield image, the picture from the camera appears way off-center. Switching back to the version I tested on August 24 solves this problem.

**Comment by kmcleaster** [comment]
During other troubleshooting, I discovered that the image appears properly if you unplug the USB from the camera, and plug it back in.

**Comment by iwaniec** [comment]
Does this happen at every start-up or just the first time?

**Comment by kmcleaster** [comment]
I am uncertain. I will need to check my notes.

We were doing some power measurements at the same time. So it might be that
a second restart of LVPro didn't get tested.

- Kevin McLeaster

**Comment by kmcleaster** [comment]
I have confirmed that this happen in all cases. When first powering up the 850 prototype, the problem occurs and closing and restarting the software, the problem occurs. To obtain a proper image from the camera, unplugging the USB cable from the hub and re-plugging it in fixes it.

**Comment by kmcleaster** [comment]
I tried an older version of LVPro that was already in place on the test computer used by Chris and Sarah. This version does **not** exhibit this problem.

**Comment by iwaniec** [comment]
Found the issue. All fixed on 10/2/22
