### ISSUE TITLE
Running Protocol with a subset of locations from the 96 Well default, cycles between location 1 and 2

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#123]
Because location 1 cannot be deleted, a 9 location Protocol  just cycles, Protocol file sent to Anna

**Comment by iwaniec** [comment]
I believe these are two different problems. Location 1 can now be deleted. Cycling from step 1 to 2 and not going further is most likely a result of your capture period being shorter than the amount of time it takes to complete a full scan. When the next scan is reached before the previous has finished, it simply drops that action and starts the next round. Need to discuss preferred action as we cannot tell in advance how long a single scan takes.
