### ISSUE TITLE
GUI- Proper Plate Well Orientation and Display

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#126]
With the  XY stage set at X=110mm, y=80mm. This screen capture shows well A12 highlighted as shown in the attached image.
![A12_110X_80_Y](https://user-images.githubusercontent.com/107218299/197876453-d1482348-774f-4139-979b-0547404b441e.png)
At this position (110,80) , this would actually be the approximate location for plate well A1.   This graphic is upside down, as rotated in the X direction.
Well A1 is always in the upper-left of a well plate. 
The lower right well in a 96 well plate is "H12" for a 96-well plate and "P24".
It may be useful to "pre-name" the plate wells when a protocol with a well plate is selected

**Comment by iwaniec** [comment]
Should be corrected now.
