### ISSUE TITLE
NEW is required for Protocol Duration and Interval to be updated in a Protocol

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#128]
changing the duration and interval in a Protocol and Saving, does not save the change.

**Comment by kmcleaster** [comment]
In other words, making the change and trying to use the same filename for the save. When you click on the Overwrite option, it does not update.

**Comment by iwaniec** [comment]
At the moment, the 'enter' button needs to be pressed to enable the change in duration and interval. This is probably why it didn't work.

**Comment by iwaniec** [comment]
Closing this as the 'enter' button for all text boxes is one master issue.
