### ISSUE TITLE
After Running "Scan and AF all Steps", running a Protocol, even with long duration and capture, cycles back

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#132]
Protocol behaves like duration and capture is too short and cycles back from 5 or 6 wells to 1.  This seems to only happen after a Scan And AF all steps" is run

**Comment by iwaniec** [comment]
Could this be caused by issue #149

**Comment by EtalumaSupport** [comment]
yes, caused by #149
