### ISSUE TITLE
Composite Image Capture not saving all channels.

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#136]
When capturing a composite image manually the red channel in the image is not being displayed.  I also am noticing a longer lag time between the green led firing and the red led firing in comparison with the lag between the blue and green leds. This lag time difference was not reproduceable, but was very noticeable when it first occurred.

**Comment by iwaniec** [comment]
The composite will follow the same set of instructions as in a protocol. That means it may go to different z values. This would delay when the leds are turned on. Also, only channels selected with the 'aquire' checkbox will become part of the final image.

**Comment by kmcleaster** [comment]
I will re-check but I am fairly certain I tested several times, insuring
that the 'acquire' checkbox was checked.

-Kevin McLeaster

**Comment by kmcleaster** [comment]
I am just getting a dark image now from the composite image capture. I verified the acquire checkbox, set focus for all channels, hit the Composite image button, waited for the shading/animation of the button to restore, looked at the image file, and it was dark. Image did not resemble the artifact I was focused upon.

**Comment by iwaniec** [comment]
hmm. I think we will need to talk in person. I am not able to reproduce this issue. The text boxes for these, as in all the others, currently require pressing the 'enter' key to be put into effect.

**Comment by EtalumaSupport** [comment]
This was most likely caused by not clicking Save Focus for each channel
