### ISSUE TITLE
GUI - Step Name Textbox not saved.

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#137]
If you attempt to add a name in the textbox for a protocol step, the name is not saved. This happens even when you save with a new protocol name. It doesn't matter if you click change and then save or just click save after entering the text.

**Comment by iwaniec** [comment]
Two issues here - 
This was specifically not working on step 1. This is fixed.
And you need to press return. This is a larger issue that is also listed elsewhere so I will close this issue.
