### ISSUE TITLE
Default File path not saved. Microscope settings and protocols saved in same folder.

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#138]
I have found that if when setting the default file path with main screen folder button, attempting to load a protocol defaults to the last folder used for saving a protocol rather than the one set with the folder icon at the bottom of the screen. I also found that the 
 load and save buttons in Microscope Settings use the same folder as protocol files. These files are mutually incompatible and will crash LVPro if one is loaded in place of the other. It seems as if the Folder Icon button at the bottom of the screen doesnt do anything.
![File_SaveScreenshot 2022-11-01](https://user-images.githubusercontent.com/107218299/199355408-d2f797e3-f4ab-480c-9a43-b719ec25ec27.png)

**Comment by iwaniec** [comment]
The folder on the bottom sets the folder that all live view and live composite images (neighboring icons) are saved. it is not connected to the protocol.
Code no longer crashes on opening an accidental non-protocol, or accidental non-settings
Filters added so it looks for the correct file type.
