### ISSUE TITLE
Load and Save buttons for Protocol and Microscope settings will pause a running protocol and a running scan

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#139]

**Comment by iwaniec** [comment]
Do we want the scan to stop or the buttons to be deactivated until the scan is stopped? I presume the later.

**Comment by kmcleaster** [comment]
I would say that the Load and New buttons need to be deactivated. The Save button seems to work without a fuss. The SaveAs button **can** remain active as long as the dialog box does not stop the running protocol. If that is difficult, a dialog box with warnings, consequences, and options would be nice. Certain timecourse studies could be compromised if a running protocol is paused too long. Chris dictates what "we" want. ;)

**Comment by EtalumaSupport** [comment]
See Issue #166

**Comment by EtalumaSupport** [comment]
Priority transferred to #166
