### ISSUE TITLE
Enable multiple channel settings to be viewed if expanded

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#14]
It is useful to see all used channels with their settings visible.  So if BF was expanded and one clicked Blue it would add below, also open.  This would continue with Green and Red and a scroll would appear if they didn't fit in the column.
![multipleChannelDisplay](https://user-images.githubusercontent.com/74261093/116166723-778cb900-a6b3-11eb-9784-427ac98a2d2d.png)

**Comment by iwaniec** [comment]
This will be very challenging as it is not part of the kivy mechanism. (Low priority)
