### ISSUE TITLE
Adding a Step in a new location overwrites other Steps when multiple channels are enabled for Acquire

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#141]
Depending on which step you do an Add from, it appears previous steps are overwritten, at least when trying to add a second location to a Protocol using the single position Center labware.  This may be due to having multiple channels enabled for Acquire.  The expected behavior would be that from any step, moving to a new location with Manual XY and pressing Add would insert multiple steps (one for each channel) at that location.

**Comment by kmcleaster** [comment]
I tried adding two additional colors the last well of a 2-color protocol by using the "Change" button. This does not work as it doesn't increase the number of steps in the protocol, it merely changes the parameters of the last step.

**Comment by kmcleaster** [comment]
I tried experimenting with adding a single step to the end of a 6well plate protocol to the stage to return to the first well. This worked for the plate movement, however the brightfield channel activated despite it being unchecked. Attaching the protocol. This protocol captures 4channels for all 6 wells, however all 4 channels on the second well are red.  The tsv extension is changed to txt . Github doesnt allow files with a tsv extension to be uploaded
[6Well_9_10_4color_well2allred2_ret_home - Copy.txt](https://github.com/EtalumaSupport/LumaViewPro/files/9956434/6Well_9_10_4color_well2allred2_ret_home.-.Copy.txt)

**Comment by kmcleaster** [comment]
> 

I found that with the 6Well plate protocol that I needed to **add** a step for each channel I wanted to capture and then set the channel and XY coordinates and click **change** each step.

**Comment by kmcleaster** [comment]
On this same protocol file, if I load it and attempt to change to another channel AFTER RUNNING THE PROTOCOL, LVPro crashes. If the change is make before the protocol is run, the change works.

**Comment by iwaniec** [comment]
I think this is a difference of expectation of what a 'step' is. In this version of LVP, a step is a singular image setting including the position and color. It does not, as in 'New Protocol', go through all the channels and adjust or add them. New insert a new setting of coordinates, imaging, and LED setttings. Modify will replace the current singular 'step' with what is currently enabled. Delete only deletes the current step.
