### ISSUE TITLE
Load Protocol does not recognize Saved Protocols

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#142]
No files are visible when clicking Load in Protocol

**Comment by iwaniec** [comment]
Protocols have been updated to tab separated values (.tsv) instead of comma separated values. There is also now a filter that will only show you files that end in .tsv. See example_protocol.tsv for latest format.

**Comment by iwaniec** [comment]
Also now allowed for *.*. However, since we are actively adjusting the performance of the protocol, the latest example will be the only one that should be guaranteed to work.
