### ISSUE TITLE
New Protocol Behavior

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#145]
When creating a new protocol, you must select which color (channels) you wish to capture in a protocol before clicking on the "New" button. Failure to do so results in the current number of steps from the previous protocol being saved if the same plate type is used.

Right now the most robust way to create a protocol seems to be to first select the channels to be acquired, the plate type, **Then click on NEW.** 

This problem is not present when starting from a clean launch of LVPro.

**Comment by iwaniec** [comment]
Much debugging done. Please test and close or comment this issue.
