### ISSUE TITLE
Crash on a new install when doing composite image

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#148]
It appears that the system will crash if you click on the composite image if you haven't saved focuses for each channel?   

Kevin M, please try to duplicate this issue and see if you can?
I think its just:

Start it up
Click on composite image on bottom.

**Comment by iwaniec** [comment]
A new install uses the default settings.json file. This has been set to 0 focus for all the channels. I have changed this to 1000. I think this is where the crash was coming from. Please test and comment or close.

**Comment by iwaniec** [comment]
Crash when going to zero should now be resolved.
