### ISSUE TITLE
Webcam comes on and stays on after launch

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#15]
Although the Basler is correctly used by the app, the PC webcam appears to be turned on as well.  Closing the app does turn it off.  This is a high priority issue.

**Comment by iwaniec** [comment]
PylonCamera class is now a child class of image instead of camera. Webcam is no longer activated or searched for. This makes the code work much faster - BUT it will no longer work with webcam so that accidental function is lost.
