### ISSUE TITLE
Logging is not verbose enough

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#156]
There are many items listed in the console but not written to the log file.  We should also add timestamps.   I think these are crucial to be able to diagnose startup issues.  (and general operation).

**Comment by iwaniec** [comment]
The plan is to transition to the logging library. https://docs.python.org/3/howto/logging.html
And implement more details.

**Comment by iwaniec** [comment]
New logging has been implemented.
