### ISSUE TITLE
Camera firmware/ streaming unreliability.  

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#158]
I got report from a customer who was using a Basler Camera with 1.0.1 firmware on it that they were having trouble with unreliability.  (NOT on LV Pro- they have their own software....).  

I think we should (if we are not already doing so) at least record the camera firmware in the log so we can see it.  We may also want to put up a message (in the log?) saying we recommend a minimum firmware.  

From Customer: 
"[1.1.0] is the one that works (version [1.0.1] gives us all sorts of trouble… Lagging image in live-view mode, slow camera response, and not being able to connect to the cameras after an instrument restart…. To connect or re-connect to the camera, we have to unplug the usb-cable (inside our instrument) or an alternative fix is to do a “device-reset” in Pylon-viewer from a service-laptop (which sometimes works..)"

Most of our cameras are 1.1.0, but the first few may be at 1.0.1.  I have never done an update on these before.  I have a ticket into Basler to get the firmware files.  Latest rev is 1.2.1.  you need to use Pylon to update the firmware.  I will update this issue with more information as I get it.

**Comment by ericweiner** [comment]
A further comment- I found a camera with 1.0.1 firmware on it- the reliability was definitely lower.  I couldn't stream at maximum bandwidth.  I updated it to 1.2.1 and all of these problems went away.    I still think we should report camera firmware in the log on startup, ideally flagging it as a problem if it is < 1.1.0.

**Comment by EtalumaSupport** [comment]
Eric, solved?

**Comment by ericweiner** [comment]
We need to record the camera firmware in the log file, as we are now doing with the motor controller. There should not be any cameras in the field < 1.1.0 but this will at least let us know if there is one if it is in the log.

**Comment by EtalumaSupport** [comment]
Is this a different issue to be added "We need to record the camera firmware in the log file, as we are now doing with the motor controller."?
