### ISSUE TITLE
App opens in reduced window causing overlap of controls

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#16]
Although we should allow resizing into this view, the default open size should not have overlapping controls.  This is a medium priority issue
![windowSizeControlsOverlap](https://user-images.githubusercontent.com/74261093/116422105-44057800-a7f4-11eb-81fd-4f19631a9e65.png)

**Comment by iwaniec** [comment]
set to auto-maximize window on start
