### ISSUE TITLE
BF Image Acquire during protocol leaves a white, blank image in the Acquire Folder

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#165]
![WhiteFailure](https://user-images.githubusercontent.com/107218299/214138276-ccec3ab9-13bd-4587-b833-a2cfb70db87a.png)

**Comment by kmcleaster** [comment]
We found that the exposure settings for BF and Phase need to be different due to Phase having more light sources that the BF setting. The dynamic range of the exposure control is large to handle Phase and Extended phase modes. However these tests were   done without a phase objective that reduces the light.

**Comment by EtalumaSupport** [comment]
This is the AG error where it enables itself in the BF channel after New, Save in Protocol
