### ISSUE TITLE
Protocol - Step Name - Two Issues

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#172]
The protocol tab now allows step names to be added to steps. The step names show up in the protocol file but are not displayed when reloading the file containing them.  They are not shown when stepping through the protocol. If step names are added on the protocol screen, the name persists across all steps when running the protocol. 

Overall the Protocol Tab seems to be much more robust and well behaved despite this exception.
![stepname 2023-02-01 165120](https://user-images.githubusercontent.com/107218299/216204904-c7ed61af-0889-428b-8a35-de148fdbdd46.png)

**Comment by iwaniec** [comment]
I believe this is currently functioning.
