### ISSUE TITLE
Save Microscope Settings file dialog - need to force .json

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#173]
When you save a microscope settings file if you do not add the .json file extension, the Load File dialog box will not display the file.
The Load File dialog only accepts .json filetype. Adding the .json extension to the created file fixes the problem and the file behaves correctly.
Loading and Saving files with the .json extension seem to work properly.
![ScopeSettings 2023-02-01 175328](https://user-images.githubusercontent.com/107218299/216212850-8213d3eb-8352-4db8-82a8-249e053d2b15.png)

**Comment by iwaniec** [comment]
Same as issue #192. closing.
