### ISSUE TITLE
Labware Offset for 12 and 24 well plates not set / incorrect

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#174]
It appears that these just haven't been calibrated or set yet.  Having a way to add specific 384, or 1536 well plates may be important.  There may be a way to use the Lumascope to obtain highly precise labware dimensions. A nice feature in labs with automation.

**Comment by EtalumaSupport** [comment]
It turns out that if you drive to the center of A1 of any plate with the provided 4x objective, the X and Y positions indicated will be the offset in the labware.json for this plate.  This is sufficient for now.
