### ISSUE TITLE
Focus Changes not saved

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#175]
When making focus changes to an existing protocol, the changes are not saved with the "Save" Button nor are they saved with "SaveAs.

**Comment by kmcleaster** [comment]
Getting the focus adjusted for the protocol requires switching between the Focus and Protocol tabs and clicking Change for each step, then a SaveAs. I haven't tried a save.

**Comment by iwaniec** [comment]
This is not the most intuitive, however, you should be able to achieve your goal by:

Go to the desired step (channel should open)
change the focus using the focus tab tools
return to the channel and click save focus
return to protocol and select change step
save protocol
