### ISSUE TITLE
Save should lead to you saving a name for a new Protocol

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#176]
Right now, if you do a New and Save, there doesn't appear to be a name saved.  Save As would be used if you have already saved and wanted to make a new named version.  Save is the first time OR overwriting the previous Save/Save As

**Comment by EtalumaSupport** [comment]
I always have to apologize during demos for Save not working as expected (not offering a new name for the file)

**Comment by tnerdi** [comment]
Now after having clicked "New", the "Save" button behaves the same as "Save As". Does this resolve the issue?
