### ISSUE TITLE
One channel (last?) has variable image brightness in 6 channel Protocol, single location

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#177]
![W_channel_issues](https://user-images.githubusercontent.com/74261093/217001440-c540985b-1c81-48c8-9571-e100ee994b40.png)

**Comment by kmcleaster** [comment]
I can't see the issue, except that the last blue and red images appear a bit dimmer.
From the script, the last channel is "3" which I believe is red.
