### ISSUE TITLE
Protocol - Deleting steps past step 0 causes crash.

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#179]
Clicling on Change for a single step protocol also causes a crash

**Comment by iwaniec** [comment]
Cannot reproduce. Please test and if no longer failing, close the issue.

**Comment by kmcleaster** [comment]
Clicking Delete on the final step is now causing a crash. It seems that the last step is in the center of the stage.

**Comment by iwaniec** [comment]
Should be fixed. Please reopen if problem persists.
