### ISSUE TITLE
Protocol - Enable LED Switch Still On

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#181]
If  BF illumination is on when starting a protocol, if the protocol is stopped the switch remains on , but the LED is off. I didn't check to see  if this happens with other channels.

**Comment by EtalumaSupport** [comment]
Asking the customer to toggle the channel after a Protocol to regain control of the LED is uncomfortable

**Comment by kmcleaster** [comment]
This has been corrected. All channels behave properly with respect to the original problem
