### ISSUE TITLE
Protocol - X,Y,Z coordinates not saved

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#182]
I was trying to create a single BF capture protocol at a single location and Focus using the Center Plate. When running, the stage moves near the center and captures images there. the BF lightpath was blocked in that location so the image was black .  Chris noticed blank BF's in a two channel protocol and ask me to check on it. I was creating this as a test.  Is it possible that the XYZ are just messed up for BF? It also appears that there is an end step or dummy step in a new protocol using BF that needs to be deleted or if it is an EOF, it needs documented.  When I went to include the .tsv to demonstrate the problem the Channel number in the file is different between two nearly identical protocols.
[OneRealBFImage2.txt](https://github.com/EtalumaSupport/LumaViewPro/files/10692833/OneRealBFImage2.txt)
[OneRealBFImage.txt](https://github.com/EtalumaSupport/LumaViewPro/files/10692834/OneRealBFImage.txt)

**Comment by iwaniec** [comment]
This will create a one channel, single position protocol:

- Deselect Acquire from all channels but bright field.
- In protocol tab: select center plate from dropdown
- select 'new' protocol
- go to step 1 of 1
- move to a new location
- select change
- save protocol

I can modify it by selecting a new channel on the right and selecting 'add' on the left. I'm not sure how you got to [OneRealBFImage2.txt](https://github.com/EtalumaSupport/LumaViewPro/files/10692833/OneRealBFImage2.txt)  
but it definitely is selecting the green channel and no brightfield. Perhaps we could do a remote runthough.

**Comment by iwaniec** [comment]
**Alternatively**:

- Deselect Acquire from all channels but bright field.
- move to a new location and settings

- In protocol tab: select center plate from dropdown
- select 'new' protocol
- save protocol
