### ISSUE TITLE
Deleting all Steps and Adding one crashes upon clicking arrows for Step advancement

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#183]
In attempting to make a completely new set of locations, I started with a Center Well and deleted all Steps (there happened to be 4) at which point the Steps said 1 of 0.  I moved to a new location and hit Add and it crashed.

**Comment by kmcleaster** [comment]
I was struggling to get just a one step protocol. With only a single channel set to **Acquire **, I clicked on **new**, **save as** (filename). Then, when I look at the resultant file with a text editor, there are two steps, one of which looks like the ( X, Y) for the stage center.

**Comment by iwaniec** [comment]
"In attempting to make a completely new set of locations, I started with a Center Well and deleted all Steps (there happened to be 4) at which point the Steps said 1 of 0. I moved to a new location and hit Add and it crashed."

repaired.

**Comment by iwaniec** [comment]
See issue #182 for creating a one step protocol.
