### ISSUE TITLE
Adjusting channels settings or changing channels in a Step, crashes when you click Change

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#185]
It appears that the channel is sacred to a Step.  Although you can change XYZ locations in a Step, if you change anything in a channel or change channels in a Step, it crashes upon clicking Change.

**Comment by kmcleaster** [comment]
"Channel" and  "Step" are essentially the same, it seems to me. Each step is an (X, Y, Z, Optical Channel) coordinate. For microplates , it may be desirable to express the step as a (PlateWellAddress, Z, Optical Channel)

**Comment by iwaniec** [comment]
Should be fixed. Please re-open in problem persists.
