### ISSUE TITLE
Stage should center upon LVP start up in addition to power/comms cycle

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#186]
Right now it will center after a comm interruption or power cycle.  It would be best to always center upon LVP launch as the first interaction is often to change the objective.

**Comment by kmcleaster** [comment]
Additionally, **the Z-Axis must travel to the "zero" position before X-Y motion commences**. Eric has raised this concern and may be a separately enumerated issue in Github. This is absolutely necessary to prevent stage collision with an objective lens.

**Comment by iwaniec** [comment]
"Right now it will center after a comm interruption or power cycle. It would be best to always center upon LVP launch as the first interaction is often to change the objective." Changes need firmware update/

"Additionally, the Z-Axis must travel to the "zero" position before X-Y motion commences. Eric has raised this concern and may be a separately enumerated issue in Github. This is absolutely necessary to prevent stage collision with an objective lens." This issue has been addressed.
