### ISSUE TITLE
Stage Controls - X and Y coordinate Displays fail to update

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#191]
If the stage is at an arbitrary position, switch to protocol, click to move to a step with a position different that the prevailing position, switch back to the stage control tab, the X & Y displays have not updated.

**Comment by iwaniec** [comment]
solved.

**Comment by kmcleaster** [comment]
X & Y Displays update now, but they don't always show the correct or expected values.

**Comment by iwaniec** [comment]
Please verify with latest version. I believe it is fixed.
