### ISSUE TITLE
Protocol - Load Button >> file dialog only shows .tsv filetype

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#192]
If you save a protocol file without supplying a .tsv extension, you can't see nor load the file because the .tsv filetype is the only file extension allowed. If the .tsv filetype could be forced at save time, this would fix the problem.  I may have caused a problem by suggesting the .tsv files. For plate protocols that are long, being able to view the file as a spreadsheet is necessary in my opinion. I thought one could open a .tsv directly in MS Excel, but that is no longer the case. It can be imported, but not opened directly. Can a tab-delimited file be saved as a .txt ? Maybe this would be a better choice. Github doesn't allow .tsv's either. In any case the dialog boxes for load and save need to be consistent. I miss the early days when these files were .csv's

**Comment by kmcleaster** [comment]
This issue is similar to https://github.com/EtalumaSupport/LumaViewPro/issues/173#issue-1567184289

**Comment by iwaniec** [comment]
Fixed to force save as *.tsv. Changing back to *.csv requires a discussion in case some of the text contains commas.

**Comment by iwaniec** [comment]
Closing this as it is two issues, One solved. If we want it to return to CSV, then lets open a new issue. Right now, when I double click on a tsv file, excel opens it correctly.
