### ISSUE TITLE
Autofocus- looks like it treats current position as the "top" rather than the center

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#193]
When I click on the autofocus button in the GUI, it appears that it treats the current position as the "top" rather than the "center".

Is this the expected behavior?  I would this it would/should use the current position as the center of the AF scan, not the top?  

(Legacy Lumaview treats the initial position as the center, so that is what my expectation is...) 

I.e. here we start at 4200 (and the _actual" focus level is @ 4470. (4x objective, in brightfield)> 

But you can see it goes to 4050 and goes around but never exceeds the initial value (4200).

TrinamicBoard.move_abs_pos(Z,4200.0) succeeded
VerticalControl.update_gui()
TrinamicBoard.target_pos(Z) succeeded
VerticalControl.autofocus()
TrinamicBoard.move_abs_pos(Z,4049.9967799999995) succeeded
Clock.schedule_interval(self.focus_iterate, 0.01)
VerticalControl.focus_iterate()
VerticalControl.focus_function()
difference      6605811.0
TrinamicBoard.move_rel_pos(Z,72.0) succeeded
VerticalControl.update_gui()
TrinamicBoard.target_pos(Z) succeeded
VerticalControl.focus_iterate()
VerticalControl.focus_function()
difference      6935799.0
TrinamicBoard.move_rel_pos(Z,72.0) succeeded
VerticalControl.update_gui()
TrinamicBoard.target_pos(Z) succeeded
VerticalControl.focus_iterate()
VerticalControl.focus_function()
difference      6367926.0
VerticalControl.focus_best()
0       4193.98442      6367926.0

TrinamicBoard.move_abs_pos(Z,4049.9884599999996) succeeded
VerticalControl.update_gui()
TrinamicBoard.target_pos(Z) succeeded
VerticalControl.focus_iterate()
VerticalControl.focus_function()
difference      7019908.0
TrinamicBoard.move_rel_pos(Z,24.0) succeeded
VerticalControl.update_gui()
TrinamicBoard.target_pos(Z) succeeded
VerticalControl.focus_iterate()
VerticalControl.focus_function()
difference      6386560.0
VerticalControl.focus_best()
1       4073.9833399999998      6386560.0

TrinamicBoard.move_abs_pos(Z,4025.9866399999996) succeeded
VerticalControl.update_gui()
TrinamicBoard.target_pos(Z) succeeded
VerticalControl.focus_iterate()
VerticalControl.focus_function()
difference      6799135.0
TrinamicBoard.move_rel_pos(Z,20.0) succeeded
VerticalControl.update_gui()
TrinamicBoard.target_pos(Z) succeeded
VerticalControl.focus_iterate()
VerticalControl.focus_function()
difference      6383684.0
VerticalControl.focus_best()
2       4045.9784       6383684.0

TrinamicBoard.move_abs_pos(Z,4025.9840799999997) succeeded
Clock.unschedule(self.focus_iterate)
Clock.unschedule(self.focus_iterate)
VerticalControl.update_gui()
TrinamicBoard.target_pos(Z) succeeded

**Comment by iwaniec** [comment]
It is supposed to use the current position as center.
It starts at the bottom (center - range) and moves up
As it moves up, once the score starts to decrease, it skips the rest of the vertical steps and starts with smaller steps below.

This strategy may need to change now that the z axis is much faster.

**Comment by ericweiner** [comment]
Maybe the display is lagging the actual position but I think the initial scan should at least get to the current position and not stop prematurely.  If the actual focus level is above the current position, as it is in my example, you never get there.  And subsequent autofocus runs lower it even more.

**Comment by kmcleaster** [comment]
I am attaching before and after AF screenshots along with a text file of the relevant transactions. After I found and focused a BF image, I set the x,y,z coordinates and then clicked on AF.
It appeared to me that the initial position was indeed used as the **center**. First image is after AF
[Autofocus Test Results from Terminal Window20230216.txt](https://github.com/EtalumaSupport/LumaViewPro/files/10761431/Autofocus.Test.Results.from.Terminal.Window20230216.txt)
![Focused Image After AF 2023-02-16 134931](https://user-images.githubusercontent.com/107218299/219500674-a23b797d-d42b-42db-a8f9-e8e647af7c94.png)
![Focused Image Before AF 2023-02-16 134931](https://user-images.githubusercontent.com/107218299/219500678-97c802dc-a539-4b44-9dab-8384b1557f58.png)

**Comment by ericweiner** [comment]
I think it would be very helpful to have a AF log that only has:
XY position (or well location), Z position, focus score.  (with time stamp) 

(maybe as something that we can enable?)

**Comment by iwaniec** [comment]
Yes. You can enable in line 111 in lumaviewpro.py by changing the line from "if False:" to if True:"

**Comment by iwaniec** [comment]
Attempt to speed up autofocus caused this error. We will try to dev a better AF but for now, the issue is fixed.
