### ISSUE TITLE
Save should have the ability to name the file

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#194]
I don't want to lose the "autosave" functionality but it would be nice if you could have a mode that would allow you to name the file that you are saving when you click on the "take image" icon. 

(Lumaview also has a "filename root" that was nice- that was easy to change and then all files would start with that.)

**Comment by EtalumaSupport** [comment]
This has been moved to High Priority.  Clicking Save the first time should make you name it.

**Comment by EtalumaSupport** [comment]
Tested today and behaves as expected.
