### ISSUE TITLE
X-Y stage start and End Coordinates reversed ?

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#197]
After manually homing the stage, the start coordinates and end coordinates seem to be transposed. See attached annotated screencapture.

![Stage start _end swapped_2023-02-16 112914](https://user-images.githubusercontent.com/107218299/219468706-d8efc334-e7f0-4f26-946b-a641b96d7867.png)

**Comment by kmcleaster** [comment]
It occurred to me that if you have the newer stage with the Hall Effect end sensors, this may be the reason for the seemingly swapped origin.

**Comment by iwaniec** [comment]
Right now, the image represents the plate, while the coordinates represent the motor positions. This will be fixed.

**Comment by iwaniec** [comment]
should be fixed to plate coordinates. Please test.
