### ISSUE TITLE
Capture button causes exit

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#2]
With hardware attached I was able to run from the shortcut generated from Jonathan's .msi.  Upon pressing Capture Image, the app closed.

**Comment by EtalumaSupport** [comment]
This occurs within the Layer Control menu as well if you click ...\capture\

**Comment by iwaniec** [comment]
The software is expecting a subfolder named capture. Since it starts empty, it disappears when creating an executable. It is on the list of things to fix.

**Comment by iwaniec** [comment]
temporary fix that it will print "save folder not found"

**Comment by iwaniec** [comment]
Since we are saving the settings automatically on close, my personal drive information was accidentally uploaded to github. This should not be an issue in general as the default folder should exist.
