### ISSUE TITLE
LVPro Froze on maximizing its window

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#202]
I was testing for missed image captures in a protocol and had the LVPro main window shrunk down to observe the filling of the selected capture folder with images. When I clicked in the window bar to maximize the window. LVPro froze. Screen capture, protocol with .txt extension, and the terminal window text are attached. I have not tested this for repeatability due to other issues.
![Screenfreeze_minimizeToMaximize 2023-03-02 113100](https://user-images.githubusercontent.com/107218299/222535173-1029ed04-9b4f-4818-8f18-e6759e76db20.png)
[Terminal_Window_Screenfreeze_minimizeToMaximize 2023-03-02 113100.txt](https://github.com/EtalumaSupport/LumaViewPro/files/10875259/Terminal_Window_Screenfreeze_minimizeToMaximize.2023-03-02.113100.txt)
[imageissuetest .txt](https://github.com/EtalumaSupport/LumaViewPro/files/10875260/imageissuetest.txt)

**Comment by iwaniec** [comment]
The terminal text is from a previous version. You can tell because the text is not preceeded with phrases such as "[LVP main  ]"

 If the problem reappears in the more recent versions since the writing of this message, please re-comment.
