### ISSUE TITLE
Interval of less than or equal to 0.04 fails to capture every frame for every channel (color) of a four channel protocol.

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#204]
Chris asked me to determine if channels with large exposure differences cause some captures to get missed. To determine this easily, I assigned each channel of a 4 color, single xyz protocol to capture each color to a different folder. When running a protocol with a 0.02 interval, the different folders had different file counts. When increasing the interval to 0.04, only the Brightfield was missing 1 single frame.  Increasing the interval to 0.05, all four separate channel folders captured the same number of images.

In the process of running this test I noticed that the file prefix for Brightfield, Phase, and Extended Phase all have the same W_ file prefix. This probably needs to be changed to Ph and EPh for the phase contrast options. If capturing to the same folder for Brightfield and Phase channels, they would be indistinguishable from one another. 

Frame loss does not seem to be related to exposure differences in this test.

**Comment by iwaniec** [comment]
"In the process of running this test I noticed that the file prefix for Brightfield, Phase, and Extended Phase all have the same W_ file prefix. This probably needs to be changed to Ph and EPh for the phase contrast options."
This is set by the user but defaults on first run based on the settings.json file. This has been updated. The other issue has not yet been addressed.
