### ISSUE TITLE
Crash after moving focus slider to the bottom, or AF

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#205]
Steps: load a familiar protocol, move to step one, turn on green ch, click autofocus, 60X objective bumps slide, drag slider to bottom >> crash.

After restarting LVPro (without USB nor powercycle) Green LED remained on. GUI shows Green LED is switched off. Toggling Green LED switch on the GUI does nothing, LED remains on.

A second restart still leaves Green LED on.

LED stays on after unplugging USB

LED goes off after unplugging Power (expected 👍 )

Repeat: Autofocus seems to do  better , this time Python Freezes, close LVPro, Green LED still on.
Plain Restart: This time the LED turned off after initializing.

**Comment by ericweiner** [comment]
crash when Z is moved to 0 is also issue #161 

This is still happening as of 4/10/23.
