### ISSUE TITLE
Homing on power up

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#207]
On 3/13/23 software. 

The first time a system is powered up, and LV pro is run, it does not do the homing routine. 

If LV pro is restarted, it does do the homing routine. (and centers it afterwards).

**Comment by ericweiner** [comment]
This is true on the latest compiled version as well (3.16.23)

Steps to reproduce:

- Depower LS850
- Power up LS850
- Start up LV Pro. 
- It does not home. 
- Close LV pro. 
- Start up LV Pro. 
- It does home. 


I think this might be related to the "is home

**Comment by kmcleaster** [comment]
Is the USB connection maintained during the power cycling?

-Kevin M

**Comment by ericweiner** [comment]
no.  Depowering the system completely disconnects the USB.  Camera + both ports/hubs go away in the device manager.

**Comment by iwaniec** [comment]
Fixed.
