### ISSUE TITLE
Save folder does not show current folder...

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#208]
When you click on the Save Destination folder icon, it comes up with a brand new folder selection dialog box.  
It would be better if this could show a fully expanded folder selection, showing where you currently are, so that you can verify that you are in the correct folder.

**Comment by jmcoreymv** [comment]
I traced this issue down to a limitation in Kivy's `plyer` codebase.  For Windows platforms, the second argument passed to the `browse`/`SHBrowseForFolder` function can be a default path selection, but `plyer` sets it to `None`.  Kivy FileChooser facade supports the `path` argument, but the lower-level plyer doesn't implement it for Window's platforms:
https://github.com/kivy/plyer/blob/d8a2b3d16b12fc54667744a092a453ad007c9448/plyer/platforms/win/filechooser.py#L135

An example value for the existing `None` argument would be something such as:
`shell.SHParseDisplayName(u"C:\test", 0)[0]`

To fix this issue, we need to either fork `plyer` and maintain the fork, or select a different library for this capability.  There's a lot of open PRs/issues for `plyer` and the latest release was last year. It doesn't seem well maintained at this point.

**Comment by jmcoreymv** [comment]
@EtalumaSupport 
I came up with a fix for this and was able to test it on Windows platforms. It may work for Mac/Linux as well, but I don't have that readily available for testing.

Fix on branch: https://github.com/EtalumaSupport/LumaViewPro/tree/bugfix/windows-dir-chooser
PR: https://github.com/EtalumaSupport/LumaViewPro/pull/268
