### ISSUE TITLE
Protocols should finish complete Scan even if Interval has been exceeded

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#217]
Prior versions of Lumaview did not require the user to estimate the length of a Scan.  This can be difficult as AF time can vary as well as Autogain.  As a result, we decided that the Scan should finish regardless of whether the Interval had been exceeded.  In this case the next Scan was initiated immediately.

**Comment by EtalumaSupport** [comment]
Customers seem to understand the consequences of too short of an interval so marked Low

**Comment by jmcoreymv** [comment]
Fixed on https://github.com/EtalumaSupport/LumaViewPro/pull/317
