### ISSUE TITLE
Objective Control shows z-position at 0, it is really at 4000 upon startup

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#220]
Clicking an up or down arrow repositions the objective icon on the slider correctly and displays the correct value

**Comment by ericweiner** [comment]
This and #219 are the same issue- Once the startup is corrected and it is able to read the position, both of these issues should be fixed.

**Comment by EtalumaSupport** [comment]
Fixed in V 1.0.0
