### ISSUE TITLE
Version 5/16 Turret control causes crash on system without turret and probably with turret

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#222]
Clicking any turret position retracts focus to 0.  From here, any attempt to move in Z or XY causes a crash.

**Comment by hickerson** [comment]
5/16 on main is not the stable version Kevin (from a phone, hence the typos)On May 17, 2023, at 9:48 AM, Etaluma Support ***@***.***> wrote:﻿
Clicking any turret position retracts focus to 0.  From here, any attempt to move in Z or XY causes a crash.

**Comment by ericweiner** [comment]
This appears to be fixes as of 6/2/2023
