### ISSUE TITLE
File naming has incorrect LED label when taking manual images

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#232]
When I select LEDs manually (not in protocol) and take images, it always says "BF" in the filename.  

These images were taken with 3 different LEDs (blue, green, red... none were with the brightfield:

06/16/2023  10:26 AM    <DIR>          .
06/16/2023  10:26 AM    <DIR>          ..
06/16/2023  10:26 AM         3,139,042 live_H12_BF_000001.tiff
06/16/2023  10:26 AM         3,146,736 live_H12_BF_000002.tiff
06/16/2023  10:26 AM         3,144,646 live_H12_BF_000003.tiff
06/16/2023  10:26 AM           287,870 live_H12_BF_000004.tiff
06/16/2023  10:26 AM         3,136,460 live_H12_BF_000005.tiff
06/16/2023  10:26 AM         3,137,304 live_H12_BF_000006.tiff
               6 File(s)     15,992,058 bytes
               2 Dir(s)  135,747,198,976 bytes free

**Comment by jmcoreymv** [comment]
@ericweiner @EtalumaSupport Do you want the image filename to use the following channel names: `BF`, `PC`, `EP`, `Blue`, `Green`, `Red` or do you want it to use the root prefix that is user-modifiable for each channel?

**Comment by ericweiner** [comment]
I think we should use whatever the Protocol uses so that it is consistent.

**Comment by jmcoreymv** [comment]
Fixed in https://github.com/EtalumaSupport/LumaViewPro/pull/272
