### ISSUE TITLE
Rolling over logs

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#233]
Right now it appears that we do not roll over logs and start a new one. (I just saw a log that is 41 MB).  I assume the logging library has rollover functionality?   We should start rolling these over at some interval and keep a certain number of files.  (i.e. 2 MB and 5 files, so 10 MB of logs will be retained) or similar to avoid this getting out of control.

**Comment by jmcoreymv** [comment]
Fixed on https://github.com/EtalumaSupport/LumaViewPro/pull/317
