### ISSUE TITLE
Step Names not used in saved image file names

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#243]
The names for steps, if entered, should be used as the first text in the saved file image name.

**Comment by EtalumaSupport** [comment]
If an unedited microplate labware is being used, A1-H12 are the standard location names.  If new locations are Added, they default to NewPos"n" incrementing up from NewPos1.  These new Step names are used as the location name in the Protocol images.  The user can edit and save these names and they are used in the image file name.

**Comment by ericweiner** [comment]
Please also see issue #232 when fixing this to see if you can do both at the same time.
