### ISSUE TITLE
Protocol generated images change format

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#252]
Issue #248 is seen in this screen shot but also a change in the format of the images.  This Protocol was 1 channel, one location, no AF.
![protocolerror](https://github.com/EtalumaSupport/LumaViewPro/assets/74261093/8b1caff4-2916-459f-9c6b-7bb2c35be31d)

The new format is full 4k, 3860 x 2178

**Comment by jmcoreymv** [comment]
I believe this is resolved with https://github.com/EtalumaSupport/LumaViewPro/pull/259
