### ISSUE TITLE
Reaction Time

### ISSUE THREAD

**Issue by iwaniec** [EtalumaSupport/LumaViewPro#26]
The widget are loaded very slowly, in windows and in linux with and without the camera. Perhaps this will help?
https://stackoverflow.com/questions/47535900/is-kivy-widgets-creation-really-so-slow-or-am-i-doing-it-wrong

Much faster as an executable but should be resolved nevertheless.

**Comment by bryantmann** [comment]
Currently working this issue

**Comment by iwaniec** [comment]
I got an executable with pylon DLLs to work and the executable is now slow. There is something here that I don't think is the widgets anymore.

**Comment by iwaniec** [comment]
(KPH)

**Comment by iwaniec** [comment]
Improved but not perfect with recent slider fix.

**Comment by iwaniec** [comment]
Resolved by pausing clock schedule for camera grabbing as kivy animations between menu items occurs.
