### ISSUE TITLE
LED remains on after Protocol completion

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#261]
The last Step in a Protocol leaves the LED on.

**Comment by EtalumaSupport** [comment]
This also occurs at the end of a "Scan and Autofocus All Steps" and if any "Scan and Autofocus All Steps" or Protocol is aborted.

**Comment by jmcoreymv** [comment]
Fixed under https://github.com/EtalumaSupport/LumaViewPro/pull/264
