### ISSUE TITLE
Activate "Open Last Save Folder"

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#271]
Allow the user to go straight to the folder where the last image was saved.  No need to have the Open Folder sub menu.

**Comment by jmcoreymv** [comment]
Should be fixed on https://github.com/EtalumaSupport/LumaViewPro/tree/dev/jcorey and will be included in next release (v1.6+).

**Comment by EtalumaSupport** [comment]
verified 1.6.1
