### ISSUE TITLE
Manual Z-stack does not return to starting point

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#287]
The focus is left at the top of the z-stack and should return to the center after acquiring the stack.

**Comment by jmcoreymv** [comment]
Should be fixed on https://github.com/EtalumaSupport/LumaViewPro/tree/dev/jcorey now, and will be included in next release (v1.6).

**Comment by EtalumaSupport** [comment]
verified in 1.6.1
