### ISSUE TITLE
Current Windows exe does not open

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#31]
On both a previously working PC with Basler Driver present as well as a clean PC without Basler Driver present, the command line opens, scrolls, and the white box appears momentarily.  This is the same behavior as early failures.

**Comment by iwaniec** [comment]
Please try the latest executable from 
https://drive.google.com/drive/folders/1I_szuj7lm418qxJWm0wzUnUD11tcDDzx?usp=sharing
It is now packed as a zip file and may resolve some issues.

**Comment by iwaniec** [comment]
Ahhh. Working on it.

**Comment by iwaniec** [comment]
I believe this issue is resolved.
