### ISSUE TITLE
Put protocol settings above the Display properties

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#315]
On lower resolution monitors, the "Acquire" check box is hidden.  this should probably be above the histogram since it will be used more often.

**Comment by jmcoreymv** [comment]
Fixed on https://github.com/EtalumaSupport/LumaViewPro/pull/317

**Comment by EtalumaSupport** [comment]
This was a problem due to screen resolution and the initial solution just hid the new lower text.  Will instruct user to adjust screen resolution.
