### ISSUE TITLE
Log rollovers

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#337]
Currently logs roll over to lumaviewpro.log.1 
It would be better to make it lumaviewpro.1.log to not break the file extension if we can.

**Comment by jmcoreymv** [comment]
Updated in the latest dev branch of `feature/12-bit` to keep the `.log` extension:
https://github.com/EtalumaSupport/LumaViewPro/tree/feature/12-bit

**Comment by jmcoreymv** [comment]
Included in 1.7.3 release.

**Comment by ericweiner** [comment]
Verified.
