### ISSUE TITLE
Multichannel tiled Steps do each channel over the tiles before changing channels and doing them all again

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#338]
I think this should do all channels in the current tile before advancing tiles.  Z differences between channels are expected to be small compared to XY tile distances.

**Comment by jmcoreymv** [comment]
Is this issue only encountered when applying tiling after protocol creation?  Or is it also encountered when tiling is part of the protocol creation?

**Comment by EtalumaSupport** [comment]
Protocol creation with tiling sequences efficiently, Added Steps do not, this might be ok for now.
