### ISSUE TITLE
LED DRIVER: improve serial communication

### ISSUE THREAD

**Issue by iwaniec** [EtalumaSupport/LumaViewPro#34]
The current version of the software seeks the first serial port available. Improve this to seek the correct serial port.

**Comment by bryantmann** [comment]
Starting work on this issue, will contact Kevin to discuss potential fixes after a careful review of that part of the code.

**Comment by iwaniec** [comment]
Currently able to manual type in COM port to a text box. This will need to change to a dropdown.

**Comment by iwaniec** [comment]
Correctly identifies LED Board port based on vid and pid:
 `        ports = serial.tools.list_ports.comports(include_links = True)
        for port in ports:
            if (port.vid == 1155) and (port.pid == 22336):
                print('LED Control Board identified at', port.device)
                self.port = port.device
                protocol['port'] = port.device`
