### ISSUE TITLE
Add timestamps for log in all modes

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#356]
Right now I think it is just in engineering/debug?  This is very helpful for troubleshooting.

**Comment by jmcoreymv** [comment]
@ericweiner Currently all logs include timestamps (engineering mode or normal), in the log file, e.g.:
```
[INFO] 04/01/2024 09:24:25.208 - lumaviewpro.py - [LVP Main  ] ModSlider.__init__()
```

However the replicated event in the console log doesn't show the timestamp, do you want this behavior changed?

**Comment by ericweiner** [comment]
Ah, my mistake.  This is working, I must have been looking at an old version.
