### ISSUE TITLE
Snap vs Acquire

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#37]
There are two approaches to getting an image.  The first is to turn on the LED, focus, snap a picture and then turn off the LED.  The second approach, which is encountered more often in traditional fluorescence microscopy, is to set the exposure, gain and illumination and acquire an image and then adjust settings and acquire another and repeat until  the image is optimized.  This keeps the excitation duration to a minimum.  The history of this approach is most likely due to lower sensitivity scopes that could not display live video fluorescence at an acceptable frame rate.  This is a lower priority function.

**Comment by iwaniec** [comment]
Not sure what the request is.

**Comment by EtalumaSupport** [comment]
Light kills cells so minimizing exposure is important.  When we take pics now, we turn on the LED, focus and acquire.  In this scenario the led is on for maybe 10 seconds. Bad but has to be done to adjust settings and focus.  Once those things are adjusted, it would be nice to acquire images with the led on for the absolute min time.  So a button that acquires an image with only 150 ms of exposure is good.  It’s what happens during a time lapse protocol and we just need a manual button for this.
Hope this helps.
Chris

**Comment by iwaniec** [comment]
As agreed, this is functionally the same as selecting only one color to acquire and choosing composite.
