### ISSUE TITLE
Ability to Control a Precise Frame Rate

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#45]
Current Lumascopes do not have a fixed frame rate as it varies based on image content and USB bandwidth.  The ability to declare a fixed frame rate is useful.  Lower priority.

**Comment by iwaniec** [comment]
I need more clarity on this question. What framerate are you referring to? Live record? display on screen?

**Comment by iwaniec** [comment]
Closed post meeting.
