### ISSUE TITLE
Turret motion for maximum safety

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#60]
This is what we should be doing to move the turret:

- Look at the current Z position. 
- Move to Z = 0. (NOT home it.  Move to Z = 0, which is a little above above the home switch.)
--This also lets you check the position of the Z during the move and make sure that we have made it.  Homing does not allow for that.  
- Once we are at Z = 0, then turn the turret.
- Move back to the original Z position.

Easy optimization:
If 4x/10x objectives are the only ones used, then we can skip this.  

We may have to still limit tall objectives.  (i.e. turret will not turn with any objective that is present on the turret that is > 42 mm or something…). 

OR: We should add objective height to the specs, and if all objectives on the turret are less than x mm, then we can spin it in place. (Or take into account the actual Z height, etc.  ). But this is all in rev 2.  

(behavior update on 6/1/23)

**Comment by EtalumaSupport** [comment]
is this the same as #234?

**Comment by ericweiner** [comment]
Yes.  I closed 234.

**Comment by jmcoreymv** [comment]
Fixed in https://github.com/EtalumaSupport/LumaViewPro/pull/274
