### ISSUE TITLE
Model Cleanup

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#62]
Right now it just has the LS850.
Eventually we want to have 3 items listed:

LS820- 3 color.  motorized Z only. (No XY, No Turret)
LS850- 3 color, motorized XY and Z (No turret)
LS850- 3 color Motorized XY, Z, and Turret.

**Comment by EtalumaSupport** [comment]
Superficial addition to dropdown with info about the motors is done. How it affects the software is not included yet.

**Comment by EtalumaSupport** [comment]
Selections are available as drop down items but they need to:
LS820-  hide XY Stage Control menu, hide turret selection
LS850- hide turret selection
LS850T- show all

**Comment by jmcoreymv** [comment]
Fixed on https://github.com/EtalumaSupport/LumaViewPro/pull/276
