### ISSUE TITLE
AVI production in POST PROCESSING

### ISSUE THREAD

**Issue by iwaniec** [EtalumaSupport/LumaViewPro#73]
- Incorporate Ori's stuff to post processing
- Tiling from folder

**Comment by EtalumaSupport** [comment]
Need AVI production from a Windows folder with images in sequence

**Comment by EtalumaSupport** [comment]
Need movie making

**Comment by EtalumaSupport** [comment]
Highlighting this as a Level 1 High Priority.

**Comment by jmcoreymv** [comment]
Added in https://github.com/EtalumaSupport/LumaViewPro/pull/275
