### ISSUE TITLE
GUI- setting numbers is difficult/buggy.

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#75]
Entering in a number in the XY or current (for example) is very frustrating.  When you select the box, it doesn't automatically select the number to let you immediately just type one in.  Or maybe this should happen if you double click it?  In any case, it is very clunky. Are there options are to change this in the GUI toolkit? 

Also- on the LED current slider (maybe others, I didn't test)- You can enter in large numbers in the text box, which makes the slider go off of the screen.  I.e. if you type in 50,000 for the current, it goes off the screen.  It doesn't appear that there are maximums enforced?

**Comment by iwaniec** [comment]
agreed.

**Comment by iwaniec** [comment]
> Entering in a number in the XY or current (for example) is very frustrating. When you select the box, it doesn't automatically select the number to let you immediately just type one in. Or maybe this should happen if you double click it? In any case, it is very clunky. Are there options are to change this in the GUI toolkit?

Additional threading changes have been made and I am no longer experiencing this issue

> Also- on the LED current slider (maybe others, I didn't test)- You can enter in large numbers in the text box, which makes the slider go off of the screen. I.e. if you type in 50,000 for the current, it goes off the screen. It doesn't appear that there are maximums enforced?

Fixed.

**Comment by ericweiner** [comment]
I didn't test it everywhere, but it does appear the "entering numbers" issue has been resolved.  It behaves much more like I would expect.

**Comment by iwaniec** [comment]
I am also having success. If this recurs, we can re-open the issue or start a new one.
