### ISSUE TITLE
GUI- LED on/off needs better feedback

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#76]
The toggle switch for each LED just slides right/left.  It should be more obvious that the LED is on or off, IMO.  Maybe we can make the slider change to the color of the other sliders when it is on?  (i.e. it turns to a color when it is on, turns back to grey when it is off).

**Comment by iwaniec** [comment]
RGB was already color coded to indicate on. Added change to brightfield to make more obvious.
