### ISSUE TITLE
Improve defaults

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#77]
Let's use the following as defaults (or at least as a starting place for defaults.)    These will be objective dependent, but at moment they are coming up with very long exposures, etc.  This is probably a better place to start out.  

BF: 
LED:  10mA?
Gain: 0
Exposure 40ms
(We will need to see what the new illuminator does- we may want to adjust in future) 

Fluorescent channels. 
LED: 150mA
Gain: Not sure, maybe 4?
Exposure: 100 ms

**Comment by iwaniec** [comment]
These settings are dynamically loaded from the settings.json file. This has been updated to reflect the values above. Changes are stored between uses of the software in current.json.
