### ISSUE TITLE
GUI- In Brightfield, a too bright image is completely black.  

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#78]
This is a bit confusing, as it makes you think that you need to turn the light/exposure/gain up, instead of down.  You really lose the image completely... Not sure if this is something that is happening in the camera or our software?  This doesn't happen in the Pylon Software, it just stays white (I believe, at least it does in streampix.)

**Comment by ericweiner** [comment]
looks like this is fixed

**Comment by iwaniec** [comment]
Previously, the range of intensity was supposed to adjust min and max values to enhance, but was not functioning correctly. This is no disabled. I recommend an enhance contrast feature that can be toggled. If you want the feature, please create a new support issue.
