### ISSUE TITLE
Crash- 0.01 exposure slider

### ISSUE THREAD

**Issue by sarahmkirk** [EtalumaSupport/LumaViewPro#79]
- change to any of the channels to exposure to 0.01 using the slider (ok if manually type in 0.01) and it will crash

**Comment by iwaniec** [comment]
exposure_t function in pyloncamera.py modified to not allow exposure setting shorter than the minimum the camera allows. In the current model being tested, that is 14 ms or 0.014 sec. Please test and close if functional.
