### ISSUE TITLE
Settings scramble on first open

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#8]
The first time you open Microscope Settings the menu is scrambled,  see pic
![SettingsScramble](https://user-images.githubusercontent.com/74261093/113191914-fb699780-9212-11eb-8d99-0d3c60285b8f.png)

**Comment by iwaniec** [comment]
High priority. Working on it.

**Comment by iwaniec** [comment]
Completed. Will package into executable.
