### ISSUE TITLE
Protocol- changes speed after x number of wells 

### ISSUE THREAD

**Issue by sarahmkirk** [EtalumaSupport/LumaViewPro#81]
When selecting the running scan option in protocol, initially it runs quickly and doesn't change speed based on the capture period or capture duration, but after it gets to a certain well (changes every time) it will slow down and take about 25 sec per well.

**Comment by iwaniec** [comment]
There were thread timing changes made July16th. Please download the latest and test again and close if functional.

**Comment by sarahmkirk** [comment]
Still changing run speed at random wells, but now it begins running at the speed it should based on inputed capture period and capture duration (if they are reasonable)

**Comment by iwaniec** [comment]
I was also experiencing this issue. I made a significant change to talking to the LED Board (close then open, write_timeout, exception handling. Please try again.

**Comment by sarahmkirk** [comment]
it is getting further into the well plate before it slows down (well 56) to 23 seconds per well (96, bright-field only)

**Comment by iwaniec** [comment]
Issue was traced to camera operation. Should be 100% responsive now.
