### ISSUE TITLE
Homing failure in Z axis

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#84]
At moment, the Z axis will fail homing if it starts at the top because it stops after 3 seconds. (comment says 4 seconds, but looks like the code says 3 seconds.)

Fixing the homing, using the limit switches in issue #61 , will solve this problem.
Alternatively, I set the timeout to 10 seconds instead of 3 and that also solves the problem.

We are getting some improved motor settings so that it will move faster, also minimizing this issue.

**Comment by iwaniec** [comment]
Agreed. Finally found the reference switch status registers for the motor controller.
TMC5072 datasheet, section 6.2.2.2

**Comment by ericweiner** [comment]
please also see the parameter list that Kevin extracted from the IDE.  
https://docs.google.com/document/d/1psonozSL9MBiI2fN50cwmij3R1j9K4QsYwgNDaCy8S4/edit#heading=h.kkl48a8r8v8x

**Comment by kmcleaster** [comment]
The RAMP_STAT register in the TMC5072 contains the status of the limit switches.
![image](https://user-images.githubusercontent.com/107218299/181351552-994f4e03-3366-4e67-af0f-a8a3b60180aa.png)

**Comment by kmcleaster** [comment]
Z - axis homing works properly now.

**Comment by kmcleaster** [comment]
Eric advises that Z-axis homing is responding to the limit switches, but the actual homing routine is not yet implemented or validated.

**Comment by iwaniec** [comment]
done :)
