### ISSUE TITLE
Doesn't run without current.json 

### ISSUE THREAD

**Issue by sarahmkirk** [EtalumaSupport/LumaViewPro#85]
Downloaded new version 7/21 and was unable to open LVP 
I tried copying over the file from an older version of LVP and it opened
Below is a screenshot after running from command prompt

![lvpcrash1](https://user-images.githubusercontent.com/108957480/180265963-c098d963-97fa-4293-9cb3-54596b9274c5.png)

**Comment by iwaniec** [comment]
Reproduced the problem and fixed it. When current.json is unavailable, settings.json is used as the default. This had a typo and is now corrected.
