### ISSUE TITLE
NEW motor controller .ini files

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#86]
The documentation isn't quite done, but these have been optimized by Kevin (and me) to improve performance.  The velocity/acceleration settings were suboptimal.  These ones should be much faster.  Note, on homing, it may jerk a bit.  IMO we should be homing using different parameters. 

Please use these ones and see how they work. 

[Optimized motor params.zip](https://github.com/EtalumaSupport/LumaViewPro/files/9163792/Optimized.motor.params.zip)

**Comment by iwaniec** [comment]
Works beautifully. Agree on homing.

**Comment by ericweiner** [comment]
<ztmotorconfig.ini>
<xymotorconfig.ini>

**Comment by iwaniec** [comment]
These work beautifully and are now part of the base code.
