### ISSUE TITLE
xy stage limits- hitting sides

### ISSUE THREAD

**Issue by sarahmkirk** [EtalumaSupport/LumaViewPro#88]
-on start the xy stage hits side if last closed in a different location
-if input a number larger than max x or y the stage hits side

**Comment by ericweiner** [comment]
I owe Anna the mechanical limits.   Maybe we can both measure ours and report them here?  
What is the maximum value for XYZ at the far limit on Proto 1 and proto 4.

**Comment by ericweiner** [comment]
Kevin found the max range of X = 122 mm, the Y is 81 mm.  

Let's simplify those ranges to:
Ranges: | mm | Microsteps
X axis (mm) | 120 | 2418898
Y axis (mm) | 80 | 1612598
Z axis (mm) | 15 | 2560000

I would also like to add 0.5mm to the XY and 0.25 mm to the Z as the initial value.  
0.5mm on XY is 10079 microsteps. 
0.25 mm on Z is 42667 microsteps 


So the usable range of X would be 10079 to 2428976
Usable range of Y would be 10079 to 1622677
Usable range of Z would be 42667 to 2602667

(This would all be a lot simpler if we could keep these in mm/um...). 
We may want to refine these numbers in the future so would be best if these could be in an ini file.

**Comment by kmcleaster** [comment]
On our prototype, after homing. I identified the distance needed to un-set the X and Y motor left limit switches.

The GUI indicates 0.06mm for both X and Y

This was determined by observing the limit switch LED's on the board achieve full brightness after successive single clicks of the button as shown. They are not always fully dim after homing. (mechanical flag position ? need pull-up/down resistor?)

![image](https://user-images.githubusercontent.com/107218299/181375722-603a8889-38d1-4e1d-b5dd-5df70797548f.png)

**Comment by ericweiner** [comment]
The limit switches will have Schmidt trigger on the final board, so they will be digital on/off on the real board.  Right now there is some fuzziness on when it triggers.  The XY is switching from optical to Hall effect switches which are also digital. But the Turret + Z will have optical, so the Schmidt triggers will help with this to sharpen the response.

**Comment by iwaniec** [comment]
Limits set.
