### ISSUE TITLE
Arrow to expand and contract menu can be out of sync

### ISSUE THREAD

**Issue by EtalumaSupport** [EtalumaSupport/LumaViewPro#9]
Changing the application window size while having the Menu open can leave the arrow pointing the wrong way and requires a toggle to re-sync.
![MenuArrowStatus](https://user-images.githubusercontent.com/74261093/113193777-353b9d80-9215-11eb-9e3a-fc4d74e1b942.png)

**Comment by bryantmann** [comment]
Resolved using on_size Window event
