### ISSUE TITLE
Need logging for LV Pro

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#93]
Ideally would have at least two levels- debug and normal.

**Comment by iwaniec** [comment]
First round of logging is implemented. And it even helped with another issue.

**Comment by kmcleaster** [comment]
I am noticing that the LVPro is continuously updating the logfile while running, increasing in size by roughly 1Kb/sec. I saved a copy, cleaned out the original, and restarted LVPro. This works fine.  I also tried deleting the LVP_log.txt. This works too, as the file is recreated by LVPro, however the logfile entries are appended, so subsequent LVPro runs have their log entries appended to LVP_log.txt. The file creation time/date header won't update unless you rename or delete LVP_log.txt between runs.

**Comment by iwaniec** [comment]
LVP logs now build new file on every startup. Also, many functions have been better coded to not be continuously called. The file size and also processing required have been reduced.
