### ISSUE TITLE
Crash? / Non-responsive - Successive Clicks on Folder Button

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#95]
When clicking on the folder icon in the main window, making a new folder, the going back to repeat this several times causes a crash.  It may be that the Choose Folder window is hidden behind the main program window.
![Folder_Play_Pause_crash1](https://user-images.githubusercontent.com/107218299/181386654-fa01338e-dc62-4235-9555-995e2e2b1c9e.png)
![Folder_Play_Pause_crash2](https://user-images.githubusercontent.com/107218299/181386727-fa74a587-b5a8-4ddf-93b6-2021222db7b6.png)
.

**Comment by kmcleaster** [comment]
Excerpt from logfile that may be revelant.
[FolderCrashLogfileExcerpt 1.txt](https://github.com/EtalumaSupport/LumaViewPro/files/9204154/FolderCrashLogfileExcerpt.1.txt)

**Comment by kmcleaster** [comment]
I found that this also occurs for the Microscope Settings controls that open a file dialog window. If you happen to click on the button twice, a 2nd file dialog appears behind LVPro so it just seems like a crash. If you leave the LVPro window and close the file dialog box(s) LVPro is still running. Multiple clicks of the file open or file save buttons will spawn multiple file dialog boxes.

**Comment by iwaniec** [comment]
It will still create multiple open windows... However, fixed bug that it crashed when selecting cancel.
