### ISSUE TITLE
GUI - Microscope Settings - Dialog box pauses protocol

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#97]
When running a protocol, if you open Microscope Settings and select load settings, a running protocol will pause until the file dialog box is closed. Generally an end user would not want to adjust the Microscope Settings in the middle of a running protocol. Some discussion with expert end users may be warranted before addressing this.
![Microscope Settings during protocol run](https://user-images.githubusercontent.com/107218299/181392749-a7df345c-a3ff-4f9f-961f-8949945fc354.png)
.

**Comment by iwaniec** [comment]
Agreed about needing discussion.

**Comment by iwaniec** [comment]
Same as issue #139. Will close this one to keep them together.
